server:
  port: 9002


spring:
  application:
    name: OWNER-SERVICE


# code below is found in the github repository

#  eureka:
#    client:
#      register-with-eureka: true
#      fetch-registry: true
#      service-url:
#        defaultZone: http://localhost:8761/eureka/
#      instance:
#        hostname: localhost